name: Update IP Blocks

on:
  schedule:
    - cron: '0 2 * * *'  # Runs daily at 2 AM UTC

  workflow_dispatch:  # Allows manual triggering from the GitHub UI

jobs:
  update-ip-blocks:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
      
    - name: Install dependencies
      run: |
        pip install requests PyGithub
      
    - name: Run the script
      run: python update_ip_blocks_nigeria.py

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m 'Auto-update IP block list'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
